# Generated by Django 5.2.8 on 2025-11-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Product',
            new_name='product',
        ),
    ]
