# Generated by Django 5.2.8 on 2025-12-09 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
