# Generated by Django 5.2.8 on 2025-12-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='date',
            new_name='created_at',
        ),
    ]
