# Generated by Django 5.2.8 on 2025-12-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviews_updated_at_alter_reviews_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='description',
            new_name='comment',
        ),
    ]
