# Generated by Django 5.2.8 on 2025-12-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_description_reviews_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='rating',
        ),
    ]
